// Auto-generated by scripts/sync-i18n.ts - DO NOT EDIT DIRECTLY
// To add a new language, simply create src/locales/<lang>.ts with a valid _meta section.

export type Language = 'en' | 'ja' | 'pt' | 'zho' | 'es' | 'vi' | 'th' | 'ko' | 'tl' | 'sw' | 'it';

export type TranslationValue = string | string[] | NestedTranslations;
export interface NestedTranslations {
    [key: string]: TranslationValue;
}

export interface LanguageConfig {
    code: Language;
    name: string;
    englishName: string;
    translationKey: string;
    flag: string;
    ldsCode: string;
}

export const LANGUAGES: readonly LanguageConfig[] = [
    {
        "code": "en",
        "name": "English",
        "englishName": "English",
        "flag": "🇺🇸",
        "ldsCode": "eng",
        "translationKey": "languages.english"
    },
    {
        "code": "ja",
        "name": "日本語",
        "englishName": "Japanese",
        "flag": "🇯🇵",
        "ldsCode": "jpn",
        "translationKey": "languages.japanese"
    },
    {
        "code": "pt",
        "name": "Português",
        "englishName": "Portuguese",
        "flag": "🇧🇷",
        "ldsCode": "por",
        "translationKey": "languages.portuguese"
    },
    {
        "code": "zho",
        "name": "繁體中文",
        "englishName": "Chinese (Traditional)",
        "flag": "🇹🇼",
        "ldsCode": "zho",
        "translationKey": "languages.chinese"
    },
    {
        "code": "es",
        "name": "Español",
        "englishName": "Spanish",
        "flag": "🇪🇸",
        "ldsCode": "spa",
        "translationKey": "languages.spanish"
    },
    {
        "code": "vi",
        "name": "Tiếng Việt",
        "englishName": "Vietnamese",
        "flag": "🇻🇳",
        "ldsCode": "vie",
        "translationKey": "languages.vietnamese"
    },
    {
        "code": "th",
        "name": "ไทย",
        "englishName": "Thai",
        "flag": "🇹🇭",
        "ldsCode": "tha",
        "translationKey": "languages.thai"
    },
    {
        "code": "ko",
        "name": "한국어",
        "englishName": "Korean",
        "flag": "🇰🇷",
        "ldsCode": "kor",
        "translationKey": "languages.korean"
    },
    {
        "code": "tl",
        "name": "Tagalog",
        "englishName": "Tagalog",
        "flag": "🇵🇭",
        "ldsCode": "tgl",
        "translationKey": "languages.tagalog"
    },
    {
        "code": "sw",
        "name": "Kiswahili",
        "englishName": "Swahili",
        "flag": "🇰🇪",
        "ldsCode": "swa",
        "translationKey": "languages.swahili"
    },
    {
        "code": "it",
        "name": "Italiano",
        "englishName": "Italian",
        "flag": "🇮🇹",
        "ldsCode": "ita",
        "translationKey": "languages.italian"
    }
] as const;

export const SUPPORTED_LANGUAGES: Language[] = LANGUAGES.map(lang => lang.code);
export const DEFAULT_LANGUAGE: Language = 'en';

export function getLanguageConfig(code: string): LanguageConfig | undefined {
    return LANGUAGES.find(lang => lang.code === code);
}

export function getLdsLanguageCode(code: string): string {
    const config = getLanguageConfig(code);
    return config ? config.ldsCode : 'eng';
}
