export const BOOK_IDENTITY_MAP: Record<string, string> = {
    "1 Chronicles": "1 Chronicles",
    "1 Corinthians": "1 Corinthians",
    "1 Corintios": "1 Corinthians",
    "1 Coríntios": "1 Corinthians",
    "1 Crónicas": "1 Chronicles",
    "1 Crônicas": "1 Chronicles",
    "1 John": "1 John",
    "1 João": "1 John",
    "1 Juan": "1 John",
    "1 Kings": "1 Kings",
    "1 Mambo ya Nyakati": "1 Chronicles",
    "1 Mga Cronica": "1 Chronicles",
    "1 Mga Hari": "1 Kings",
    "1 Mga Taga-Corinto": "1 Corinthians",
    "1 Mga Taga-Tesalonica": "1 Thessalonians",
    "1 Nefi": "1 Nephi",
    "1 Nephi": "1 Nephi",
    "1 Néfi": "1 Nephi",
    "1 Nê Phi": "1 Nephi",
    "1 Pedro": "1 Peter",
    "1 Peter": "1 Peter",
    "1 Petro": "1 Peter",
    "1 Reis": "1 Kings",
    "1 Reyes": "1 Kings",
    "1 Samuel": "1 Samuel",
    "1 Samweli": "1 Samuel",
    "1 Tesalonicenses": "1 Thessalonians",
    "1 Tessalonicenses": "1 Thessalonians",
    "1 Thessalonians": "1 Thessalonians",
    "1 Timoteo": "1 Timothy",
    "1 Timotheo": "1 Timothy",
    "1 Timothy": "1 Timothy",
    "1 Timóteo": "1 Timothy",
    "1 Wafalme": "1 Kings",
    "1 Wakorintho": "1 Corinthians",
    "1 Wathesalonike": "1 Thessalonians",
    "1 Yohana": "1 John",
    "1 ซามูเอล": "1 Samuel",
    "1 ทิโมธี": "1 Timothy",
    "1 นีไฟ": "1 Nephi",
    "1 พงศาวดาร": "1 Chronicles",
    "1 พงศ์กษัตริย์": "1 Kings",
    "1 ยอห์น": "1 John",
    "1 เธสะโลนิกา": "1 Thessalonians",
    "1 เปโตร": "1 Peter",
    "1 โครินธ์": "1 Corinthians",
    "2 Chronicles": "2 Chronicles",
    "2 Corinthians": "2 Corinthians",
    "2 Corintios": "2 Corinthians",
    "2 Coríntios": "2 Corinthians",
    "2 Crónicas": "2 Chronicles",
    "2 Crônicas": "2 Chronicles",
    "2 John": "2 John",
    "2 João": "2 John",
    "2 Juan": "2 John",
    "2 Kings": "2 Kings",
    "2 Mambo ya Nyakati": "2 Chronicles",
    "2 Mga Cronica": "2 Chronicles",
    "2 Mga Hari": "2 Kings",
    "2 Mga Taga-Corinto": "2 Corinthians",
    "2 Mga Taga-Tesalonica": "2 Thessalonians",
    "2 Nefi": "2 Nephi",
    "2 Nephi": "2 Nephi",
    "2 Néfi": "2 Nephi",
    "2 Nê Phi": "2 Nephi",
    "2 Pedro": "2 Peter",
    "2 Peter": "2 Peter",
    "2 Petro": "2 Peter",
    "2 Reis": "2 Kings",
    "2 Reyes": "2 Kings",
    "2 Samuel": "2 Samuel",
    "2 Samweli": "2 Samuel",
    "2 Tesalonicenses": "2 Thessalonians",
    "2 Tessalonicenses": "2 Thessalonians",
    "2 Thessalonians": "2 Thessalonians",
    "2 Timoteo": "2 Timothy",
    "2 Timotheo": "2 Timothy",
    "2 Timothy": "2 Timothy",
    "2 Timóteo": "2 Timothy",
    "2 Wafalme": "2 Kings",
    "2 Wakorintho": "2 Corinthians",
    "2 Wathesalonike": "2 Thessalonians",
    "2 Yohana": "2 John",
    "2 ซามูเอล": "2 Samuel",
    "2 ทิโมธี": "2 Timothy",
    "2 นีไฟ": "2 Nephi",
    "2 พงศาวดาร": "2 Chronicles",
    "2 พงศ์กษัตริย์": "2 Kings",
    "2 ยอห์น": "2 John",
    "2 เธสะโลนิกา": "2 Thessalonians",
    "2 เปโตร": "2 Peter",
    "2 โครินธ์": "2 Corinthians",
    "3 John": "3 John",
    "3 João": "3 John",
    "3 Juan": "3 John",
    "3 Nefi": "3 Nephi",
    "3 Nephi": "3 Nephi",
    "3 Néfi": "3 Nephi",
    "3 Nê Phi": "3 Nephi",
    "3 Yohana": "3 John",
    "3 นีไฟ": "3 Nephi",
    "3 ยอห์น": "3 John",
    "4 Nefi": "4 Nephi",
    "4 Nephi": "4 Nephi",
    "4 Néfi": "4 Nephi",
    "4 Nê Phi": "4 Nephi",
    "4 นีไฟ": "4 Nephi",
    "A Família: Proclamação ao Mundo": "The Family Proclamation",
    "Abdías": "Obadiah",
    "Abraham": "Abraham",
    "Abraão": "Abraham",
    "Acts": "Acts",
    "Ageu": "Haggai",
    "Alma": "Alma",
    "Amos": "Amos",
    "Amosi": "Amos",
    "Amós": "Amos",
    "An Ma": "Alma",
    "Ang Awit ni Solomon": "Song of Solomon",
    "Ang Buhay na Cristo": "The Living Christ",
    "Ang Pagpapahayag sa Mag-anak": "The Family Proclamation",
    "Ang Proklamasyon ng Pagpapanumbalik": "Restoration Proclamation",
    "Apocalipse": "Revelation",
    "Apocalipsis": "Revelation",
    "Articles of Faith": "Articles of Faith",
    "Artículos de Fe": "Articles of Faith",
    "Atos": "Acts",
    "Ayubu": "Job",
    "Baptism Ordinance": "Baptism Ordinance",
    "Bản Tuyên Ngôn về Gia Đình": "The Family Proclamation",
    "Bản Tuyên Ngôn về Sự Phục Hồi": "Restoration Proclamation",
    "Cantares": "Song of Solomon",
    "Colosenses": "Colossians",
    "Colossenses": "Colossians",
    "Colossians": "Colossians",
    "Cânticos": "Song of Solomon",
    "D&C": "D&C",
    "Daniel": "Daniel",
    "Danieli": "Daniel",
    "Deuteronomio": "Deuteronomy",
    "Deuteronomy": "Deuteronomy",
    "Deuteronômio": "Deuteronomy",
    "Doctrina y Convenios": "Doctrine and Covenants",
    "Doctrine and Covenants": "Doctrine and Covenants",
    "Doktrina at mga Tipan": "Doctrine and Covenants",
    "Doutrina e Convênios": "Doctrine and Covenants",
    "Ecclesiastes": "Ecclesiastes",
    "Eclesiastes": "Ecclesiastes",
    "Eclesiastés": "Ecclesiastes",
    "Efesios": "Ephesians",
    "Efésios": "Ephesians",
    "El Cristo Viviente": "The Living Christ",
    "Enos": "Enos",
    "Enoshi": "Enos",
    "Enós": "Enos",
    "Ephesians": "Ephesians",
    "Esdras": "Ezra",
    "Esta": "Esther",
    "Ester": "Esther",
    "Esther": "Esther",
    "Eter": "Ether",
    "Ether": "Ether",
    "Etheri": "Ether",
    "Exodo": "Exodus",
    "Exodus": "Exodus",
    "Ezekiel": "Ezekiel",
    "Ezekieli": "Ezekiel",
    "Ezequiel": "Ezekiel",
    "Ezra": "Ezra",
    "Familia: Tangazo kwa Ulimwengu": "The Family Proclamation",
    "Filemom": "Philemon",
    "Filemon": "Philemon",
    "Filemoni": "Philemon",
    "Filemón": "Philemon",
    "Filipenses": "Philippians",
    "Galatians": "Galatians",
    "Genesis": "Genesis",
    "Gia Cốp": "Jacob",
    "Gia Rôm": "Jarom",
    "Giáo Lý và Giao Ước": "Doctrine and Covenants",
    "Giáo Lễ Báp Têm": "Baptism Ordinance",
    "Giô Sép Smith—Lịch Sử": "Joseph Smith-History",
    "Giô Sép Smith—Ma Thi Ơ": "Joseph Smith-Matthew",
    "Gálatas": "Galatians",
    "Génesis": "Genesis",
    "Gênesis": "Genesis",
    "Habacuc": "Habakkuk",
    "Habacuque": "Habakkuk",
    "Habakkuk": "Habakkuk",
    "Habakuki": "Habakkuk",
    "Hagai": "Haggai",
    "Hageo": "Haggai",
    "Haggai": "Haggai",
    "Hebreos": "Hebrews",
    "Hebreus": "Hebrews",
    "Hebrews": "Hebrews",
    "Hechos": "Acts",
    "Helaman": "Helaman",
    "Helamani": "Helaman",
    "Helamán": "Helaman",
    "Helamã": "Helaman",
    "Hesabu": "Numbers",
    "Hosea": "Hosea",
    "Hê La Man": "Helaman",
    "Ibada ya Ubatizo": "Baptism Ordinance",
    "Ibrahimu": "Abraham",
    "Isaiah": "Isaiah",
    "Isaias": "Isaiah",
    "Isaya": "Isaiah",
    "Isaías": "Isaiah",
    "Jacob": "Jacob",
    "Jacó": "Jacob",
    "James": "James",
    "Jarom": "Jarom",
    "Jeremiah": "Jeremiah",
    "Jeremias": "Jeremiah",
    "Jeremías": "Jeremiah",
    "Job": "Job",
    "Joel": "Joel",
    "John": "John",
    "Jonah": "Jonah",
    "Jonas": "Jonah",
    "Jonás": "Jonah",
    "Joseph Smith-History": "Joseph Smith-History",
    "Joseph Smith-Matthew": "Joseph Smith-Matthew",
    "Joseph Smith—Historia": "Joseph Smith-History",
    "Joseph Smith—História": "Joseph Smith-History",
    "Joseph Smith—Kasaysayan": "Joseph Smith-History",
    "Joseph Smith—Mateo": "Joseph Smith-Matthew",
    "Joseph Smith—Mateus": "Joseph Smith-Matthew",
    "Joseph Smith—Mathayo": "Joseph Smith-Matthew",
    "Joshua": "Joshua",
    "Josue": "Joshua",
    "Josué": "Joshua",
    "José Smith—Historia": "Joseph Smith-History",
    "José Smith—Mateo": "Joseph Smith-Matthew",
    "João": "John",
    "Juan": "John",
    "Judas": "Jude",
    "Jude": "Jude",
    "Judges": "Judges",
    "Jueces": "Judges",
    "Juízes": "Judges",
    "Jó": "Job",
    "Kristo Aliye Hai": "The Living Christ",
    "Kumbukumbu la Torati": "Deuteronomy",
    "Kutoka": "Exodus",
    "La proclamación sobre la familia": "The Family Proclamation",
    "Lamentaciones": "Lamentations",
    "Lamentations": "Lamentations",
    "Lamentações": "Lamentations",
    "Levitico": "Leviticus",
    "Leviticus": "Leviticus",
    "Levítico": "Leviticus",
    "Lucas": "Luke",
    "Luka": "Luke",
    "Luke": "Luke",
    "Lời Mặc Môn": "Words of Mormon",
    "Mafundisho na Maagano": "Doctrine and Covenants",
    "Makala ya Imani": "Articles of Faith",
    "Malachi": "Malachi",
    "Malaki": "Malachi",
    "Malakias": "Malachi",
    "Malaquias": "Malachi",
    "Malaquías": "Malachi",
    "Mambo ya Walawi": "Leviticus",
    "Maneno ya Mormoni": "Words of Mormon",
    "Maombi ya Sakramenti": "Sacrament Prayers",
    "Maombolezo": "Lamentations",
    "Marcos": "Mark",
    "Mark": "Mark",
    "Marko": "Mark",
    "Matendo ya Mitume": "Acts",
    "Mateo": "Matthew",
    "Mateus": "Matthew",
    "Mathayo": "Matthew",
    "Matthew": "Matthew",
    "Mga Awit": "Psalms",
    "Mga Bilang": "Numbers",
    "Mga Gawa": "Acts",
    "Mga Hebreo": "Hebrews",
    "Mga Hukom": "Judges",
    "Mga Kawikaan": "Proverbs",
    "Mga Panaghoy": "Lamentations",
    "Mga Panalangin sa Sakramento": "Sacrament Prayers",
    "Mga Saligan ng Pananampalataya": "Articles of Faith",
    "Mga Taga-Colosas": "Colossians",
    "Mga Taga-Efeso": "Ephesians",
    "Mga Taga-Filipos": "Philippians",
    "Mga Taga-Galacia": "Galatians",
    "Mga Taga-Roma": "Romans",
    "Mhubiri": "Ecclesiastes",
    "Micah": "Micah",
    "Mika": "Micah",
    "Mikas": "Micah",
    "Miqueas": "Micah",
    "Miquéias": "Micah",
    "Mithali": "Proverbs",
    "Moises": "Moses",
    "Moisés": "Moses",
    "Mormon": "Mormon",
    "Mormoni": "Mormon",
    "Mormón": "Mormon",
    "Moroni": "Moroni",
    "Morôni": "Moroni",
    "Moses": "Moses",
    "Mosia": "Mosiah",
    "Mosiah": "Mosiah",
    "Mosias": "Mosiah",
    "Mosíah": "Mosiah",
    "Musa": "Moses",
    "Mwanzo": "Genesis",
    "Mórmon": "Mormon",
    "Mô Rô Ni": "Moroni",
    "Mô Si A": "Mosiah",
    "Môi Se": "Moses",
    "Mặc Môn": "Mormon",
    "Nahum": "Nahum",
    "Nahumu": "Nahum",
    "Nahúm": "Nahum",
    "Naum": "Nahum",
    "Neemias": "Nehemiah",
    "Nehemia": "Nehemiah",
    "Nehemiah": "Nehemiah",
    "Nehemias": "Nehemiah",
    "Nehemías": "Nehemiah",
    "Những Lời Cầu Nguyện Tiệc Thánh": "Sacrament Prayers",
    "Những Tín Điều": "Articles of Faith",
    "Numbers": "Numbers",
    "Números": "Numbers",
    "O Cristo Vivo": "The Living Christ",
    "Obadia": "Obadiah",
    "Obadiah": "Obadiah",
    "Obadias": "Obadiah",
    "Omni": "Omni",
    "Oraciones sacramentales": "Sacrament Prayers",
    "Orações Sacramentais": "Sacrament Prayers",
    "Ordenanza del bautismo": "Baptism Ordinance",
    "Ordenança do Batismo": "Baptism Ordinance",
    "Oseas": "Hosea",
    "Oséias": "Hosea",
    "Palabras de Mormón": "Words of Mormon",
    "Palavras de Mórmon": "Words of Mormon",
    "Philemon": "Philemon",
    "Philippians": "Philippians",
    "Proclamación sobre la Restauración": "Restoration Proclamation",
    "Proclamação da Restauração": "Restoration Proclamation",
    "Proverbios": "Proverbs",
    "Proverbs": "Proverbs",
    "Provérbios": "Proverbs",
    "Psalms": "Psalms",
    "Regras de Fé": "Articles of Faith",
    "Restoration Proclamation": "Restoration Proclamation",
    "Revelation": "Revelation",
    "Romanos": "Romans",
    "Romans": "Romans",
    "Rut": "Ruth",
    "Rute": "Ruth",
    "Ruth": "Ruth",
    "Ruthi": "Ruth",
    "Sacrament Prayers": "Sacrament Prayers",
    "Salita ni Mormon": "Words of Mormon",
    "Salmos": "Psalms",
    "Santiago": "James",
    "Sefania": "Zephaniah",
    "Sofonias": "Zephaniah",
    "Sofonías": "Zephaniah",
    "Song of Solomon": "Song of Solomon",
    "Tangazo la Urejesho": "Restoration Proclamation",
    "The Family Proclamation": "The Family Proclamation",
    "The Living Christ": "The Living Christ",
    "Tiago": "James",
    "Tito": "Titus",
    "Titus": "Titus",
    "Ufunuo": "Revelation",
    "Waamuzi": "Judges",
    "Waebrania": "Hebrews",
    "Waefeso": "Ephesians",
    "Wafilipi": "Philippians",
    "Wagalatia": "Galatians",
    "Wakolosai": "Colossians",
    "Warumi": "Romans",
    "Wimbo Ulio Bora": "Song of Solomon",
    "Words of Mormon": "Words of Mormon",
    "Yakobo": "Jacob",
    "Yaromu": "Jarom",
    "Yeremia": "Jeremiah",
    "Yoeli": "Joel",
    "Yohana": "John",
    "Yona": "Jonah",
    "Yoshua": "Joshua",
    "Yuda": "Jude",
    "Zaburi": "Psalms",
    "Zacarias": "Zechariah",
    "Zacarías": "Zechariah",
    "Zechariah": "Zechariah",
    "Zefanias": "Zephaniah",
    "Zekaria": "Zechariah",
    "Zephaniah": "Zephaniah",
    "Áp Ra Ham": "Abraham",
    "Éter": "Ether",
    "Éxodo": "Exodus",
    "Ê Nốt": "Enos",
    "Ê The": "Ether",
    "Êxodo": "Exodus",
    "Ôm Ni": "Omni",
    "Ômni": "Omni",
    "Đấng Ky Tô Hằng Sống": "The Living Christ",
    "กันดารวิถี": "Numbers",
    "กาลาเทีย": "Galatians",
    "กิจการ": "Acts",
    "คำสวดอ้อนวอนศีลระลึก": "Sacrament Prayers",
    "จารอม": "Jarom",
    "ดาเนียล": "Daniel",
    "ถ้อยคำของมอรมอน": "Words of Mormon",
    "ถ้อยแถลงเรื่องการฟื้นฟู": "Restoration Proclamation",
    "ถ้อยแถลงเรื่องครอบครัว": "The Family Proclamation",
    "ทิตัส": "Titus",
    "นางรูธ": "Ruth",
    "นาฮูม": "Nahum",
    "ปฐมกาล": "Genesis",
    "ปัญญาจารย์": "Ecclesiastes",
    "ผู้วินิจฉัย": "Judges",
    "พระคริสต์ผู้ทรงพระชนม์": "The Living Christ",
    "ฟิลิปปี": "Philippians",
    "ฟีเลโมน": "Philemon",
    "มอรมอน": "Mormon",
    "มัทธิว": "Matthew",
    "มาระโก": "Mark",
    "มาลาคี": "Malachi",
    "มีคาห์": "Micah",
    "ยอห์น": "John",
    "ยากอบ": "James",
    "ยาคอบ": "Jacob",
    "ยูดา": "Jude",
    "ลูกา": "Luke",
    "วิวรณ์": "Revelation",
    "สดุดี": "Psalms",
    "สุภาษิต": "Proverbs",
    "หลักคำสอนและพันธสัญญา": "Doctrine and Covenants",
    "หลักแห่งความเชื่อ": "Articles of Faith",
    "อพยพ": "Exodus",
    "ออมไน": "Omni",
    "อับราฮัม": "Abraham",
    "อาโมส": "Amos",
    "อิสยาห์": "Isaiah",
    "อีนัส": "Enos",
    "อีเธอร์": "Ether",
    "ฮักกัย": "Haggai",
    "ฮาบากุก": "Habakkuk",
    "ฮีบรู": "Hebrews",
    "ฮีลามัน": "Helaman",
    "เฉลยธรรมบัญญัติ": "Deuteronomy",
    "เนหะมีย์": "Nehemiah",
    "เพลงคร่ำครวญ": "Lamentations",
    "เพลงไพเราะ": "Song of Solomon",
    "เยเรมีย์": "Jeremiah",
    "เลวีนิติ": "Leviticus",
    "เศคาริยาห์": "Zechariah",
    "เศฟันยาห์": "Zephaniah",
    "เอสรา": "Ezra",
    "เอสเธอร์": "Esther",
    "เอเฟซัส": "Ephesians",
    "เอเสเคียล": "Ezekiel",
    "แอลมา": "Alma",
    "โคโลสี": "Colossians",
    "โจเซฟ สมิธ—ประวัติ": "Joseph Smith-History",
    "โจเซฟ สมิธ—มัทธิว": "Joseph Smith-Matthew",
    "โมเสส": "Moses",
    "โมโรไน": "Moroni",
    "โมไซยาห์": "Mosiah",
    "โยชูวา": "Joshua",
    "โยนาห์": "Jonah",
    "โยบ": "Job",
    "โยเอล": "Joel",
    "โรม": "Romans",
    "โอบาดีห์": "Obadiah",
    "โฮเชยา": "Hosea",
    "アブラハム書": "Abraham",
    "アモス書": "Amos",
    "アルマ書": "Alma",
    "イザヤ書": "Isaiah",
    "エステル記": "Esther",
    "エズラ記": "Ezra",
    "エゼキエル書": "Ezekiel",
    "エテル書": "Ether",
    "エノス書": "Enos",
    "エペソ人への手紙": "Ephesians",
    "エレミヤ書": "Jeremiah",
    "オバデヤ書": "Obadiah",
    "オムナイ書": "Omni",
    "ガラテヤ人への手紙": "Galatians",
    "コリント人への第一の手紙": "1 Corinthians",
    "コリント人への第二の手紙": "2 Corinthians",
    "コロサイ人への手紙": "Colossians",
    "サムエル記上": "1 Samuel",
    "サムエル記下": "2 Samuel",
    "ジェロム書": "Jarom",
    "ジョセフ・スミス—マタイ": "Joseph Smith-Matthew",
    "ジョセフ・スミス—歴史": "Joseph Smith-History",
    "ゼカリヤ書": "Zechariah",
    "ゼパニヤ書": "Zephaniah",
    "ダニエル書": "Daniel",
    "テサロニケ人への第一の手紙": "1 Thessalonians",
    "テサロニケ人への第二の手紙": "2 Thessalonians",
    "テトスへの手紙": "Titus",
    "テモテへの第一の手紙": "1 Timothy",
    "テモテへの第二の手紙": "2 Timothy",
    "ナホム書": "Nahum",
    "ニーファイ第一書": "1 Nephi",
    "第1ニーファイ": "1 Nephi",
    "第１ニーファイ": "1 Nephi",
    "第一ニーファイ": "1 Nephi",
    "ニーファイ第二書": "2 Nephi",
    "第2ニーファイ": "2 Nephi",
    "第２ニーファイ": "2 Nephi",
    "第二ニーファイ": "2 Nephi",
    "第三ニーファイ": "3 Nephi",
    "第3ニーファイ": "3 Nephi",
    "第３ニーファイ": "3 Nephi",
    "第四ニーファイ": "4 Nephi",
    "第4ニーファイ": "4 Nephi",
    "第４ニーファイ": "4 Nephi",
    "ネヘミヤ記": "Nehemiah",
    "ハガイ書": "Haggai",
    "ハバクク書": "Habakkuk",
    "バプテスマの儀式": "Baptism Ordinance",
    "ヒラマン書": "Helaman",
    "ピリピ人への手紙": "Philippians",
    "ヘブル人への手紙": "Hebrews",
    "ペテロの第一の手紙": "1 Peter",
    "ペテロ of the Second Letter": "2 Peter",
    "ペテロの第二の手紙": "2 Peter",
    "ホセア書": "Hosea",
    "マタイによる福音書": "Matthew",
    "マラキ書": "Malachi",
    "マルコによる福音書": "Mark",
    "ミカ書": "Micah",
    "モルモンの言葉": "Words of Mormon",
    "モルモン書": "Mormon",
    "モロナイ書": "Moroni",
    "モーサヤ書": "Mosiah",
    "モーセ書": "Moses",
    "ヤコブの手紙": "James",
    "ヤコブ書": "Jacob",
    "ユダの手紙": "Jude",
    "ヨエル書": "Joel",
    "ヨシュア記": "Joshua",
    "ヨナ書": "Jonah",
    "ヨハネによる福音書": "John",
    "ヨハネの第一の手紙": "1 John",
    "ヨハネの第三の手紙": "3 John",
    "ヨハネの第二の手紙": "2 John",
    "ヨハネの黙示録": "Revelation",
    "ヨブ記": "Job",
    "ルカによる福音書": "Luke",
    "ルツ記": "Ruth",
    "レビ記": "Leviticus",
    "ローマ人への手紙": "Romans",
    "亞伯拉罕書": "Abraham",
    "以帖書": "Ether",
    "以弗所書": "Ephesians",
    "以挪士書": "Enos",
    "以斯帖記": "Esther",
    "以斯拉記": "Ezra",
    "以西結書": "Ezekiel",
    "以賽亞書": "Isaiah",
    "伝道の書": "Ecclesiastes",
    "但以理書": "Daniel",
    "何西阿書": "Hosea",
    "使徒行伝": "Acts",
    "使徒行傳": "Acts",
    "俄巴底亞書": "Obadiah",
    "信仰箇条": "Articles of Faith",
    "信條": "Articles of Faith",
    "傳道書": "Ecclesiastes",
    "出エジプト記": "Exodus",
    "出埃及記": "Exodus",
    "列王紀上": "1 Kings",
    "列王紀下": "2 Kings",
    "列王記上": "1 Kings",
    "列王記下": "2 Kings",
    "利未記": "Leviticus",
    "創世記": "Genesis",
    "加拉太書": "Galatians",
    "哀歌": "Lamentations",
    "哈巴谷書": "Habakkuk",
    "哈該書": "Haggai",
    "哥林多前書": "1 Corinthians",
    "哥林多後書": "2 Corinthians",
    "啟示錄": "Revelation",
    "回復の宣言": "Restoration Proclamation",
    "士師記": "Judges",
    "奧姆奈書": "Omni",
    "家庭：致全世界文告": "The Family Proclamation",
    "家族の宣言": "The Family Proclamation",
    "尼希米記": "Nehemiah",
    "尼腓一書": "1 Nephi",
    "尼腓三書": "3 Nephi",
    "尼腓二書": "2 Nephi",
    "尼腓四書": "4 Nephi",
    "希伯來書": "Hebrews",
    "希拉曼書": "Helaman",
    "帖撒羅尼迦前書": "1 Thessalonians",
    "帖撒羅尼迦後書": "2 Thessalonians",
    "彌迦書": "Micah",
    "彼得前書": "1 Peter",
    "彼得後書": "2 Peter",
    "復興文告": "Restoration Proclamation",
    "提多書": "Titus",
    "提摩太前書": "1 Timothy",
    "提摩太後書": "2 Timothy",
    "摩爾門書": "Mormon",
    "摩爾門語": "Words of Mormon",
    "摩羅乃書": "Moroni",
    "摩西書": "Moses",
    "摩賽亞書": "Mosiah",
    "撒母耳記上": "1 Samuel",
    "撒母耳記下": "2 Samuel",
    "撒迦利亞書": "Zechariah",
    "教義と聖約": "Doctrine and Covenants",
    "教義和聖約": "Doctrine and Covenants",
    "歌羅西書": "Colossians",
    "歴代誌上": "1 Chronicles",
    "歴代誌下": "2 Chronicles",
    "歷代志上": "1 Chronicles",
    "歷代志下": "2 Chronicles",
    "民数記": "Numbers",
    "民數記": "Numbers",
    "洗禮教儀": "Baptism Ordinance",
    "活著的基督": "The Living Christ",
    "猶大書": "Jude",
    "瑪拉基書": "Malachi",
    "生けるキリスト": "The Living Christ",
    "申命記": "Deuteronomy",
    "箴言": "Proverbs",
    "約伯記": "Job",
    "約拿書": "Jonah",
    "約書亞記": "Joshua",
    "約珥書": "Joel",
    "約瑟·斯密——歷史": "Joseph Smith-History",
    "約瑟·斯密——馬太": "Joseph Smith-Matthew",
    "約翰一書": "1 John",
    "約翰三書": "3 John",
    "約翰二書": "2 John",
    "約翰福音": "John",
    "羅馬書": "Romans",
    "耶利米哀歌": "Lamentations",
    "耶利米書": "Jeremiah",
    "聖餐の祈り": "Sacrament Prayers",
    "聖餐祈禱文": "Sacrament Prayers",
    "腓利門書": "Philemon",
    "腓立比書": "Philippians",
    "西番雅書": "Zephaniah",
    "詩篇": "Psalms",
    "路加福音": "Luke",
    "路得記": "Ruth",
    "那鴻書": "Nahum",
    "阿摩司書": "Amos",
    "阿爾瑪書": "Alma",
    "雅各書": "Jacob",
    "雅歌": "Song of Solomon",
    "雅龍書": "Jarom",
    "馬可福音": "Mark",
    "馬太福音": "Matthew",
    "가족 선언문": "The Family Proclamation",
    "갈라디아서": "Galatians",
    "고린도전서": "1 Corinthians",
    "고린도후서": "2 Corinthians",
    "골로새서": "Colossians",
    "교리와 성약": "Doctrine and Covenants",
    "나훔": "Nahum",
    "누가복음": "Luke",
    "느헤미야": "Nehemiah",
    "니파이전서": "1 Nephi",
    "니파이후서": "2 Nephi",
    "다니엘": "Daniel",
    "데살로니가전서": "1 Thessalonians",
    "데살로니가후서": "2 Thessalonians",
    "디도서": "Titus",
    "디모데전서": "1 Timothy",
    "디모데후서": "2 Timothy",
    "레위기": "Leviticus",
    "로마서": "Romans",
    "룻기": "Ruth",
    "마가복음": "Mark",
    "마태복음": "Matthew",
    "말라기": "Malachi",
    "모로나이서": "Moroni",
    "모사이야서": "Mosiah",
    "모세서": "Moses",
    "몰몬서": "Mormon",
    "몰몬의 말씀": "Words of Mormon",
    "미가": "Micah",
    "민수기": "Numbers",
    "베드로전서": "1 Peter",
    "베드로후서": "2 Peter",
    "빌레몬서": "Philemon",
    "빌립보서": "Philippians",
    "사도행전": "Acts",
    "사무엘상": "1 Samuel",
    "사무엘하": "2 Samuel",
    "사사기": "Judges",
    "살า 계신 그리스도": "The Living Christ",
    "성찬 기도": "Sacrament Prayers",
    "스가랴": "Zechariah",
    "스바냐": "Zephaniah",
    "시편": "Psalms",
    "신명기": "Deuteronomy",
    "신앙개조": "Articles of Faith",
    "아가": "Song of Solomon",
    "아모스": "Amos",
    "아브라함서": "Abraham",
    "앨마서": "Alma",
    "야고보서": "James",
    "야곱서": "Jacob",
    "에베소서": "Ephesians",
    "에스겔": "Ezekiel",
    "에스더": "Esther",
    "에스라": "Ezra",
    "여호수아": "Joshua",
    "역대상": "1 Chronicles",
    "역대하": "2 Chronicles",
    "열왕기상": "1 Kings",
    "열왕기하": "2 Kings",
    "예레미야": "Jeremiah",
    "예레미야애가": "Lamentations",
    "예이롬서": "Jarom",
    "오바댜": "Obadiah",
    "옴나이서": "Omni",
    "요나": "Jonah",
    "요엘": "Joel",
    "요한1서": "1 John",
    "요한2서": "2 John",
    "요한3서": "3 John",
    "요한계시록": "Revelation",
    "요한복음": "John",
    "욥기": "Job",
    "유다서": "Jude",
    "이노스서": "Enos",
    "이더서": "Ether",
    "이사야": "Isaiah",
    "잠언": "Proverbs",
    "전도서": "Ecclesiastes",
    "제3니파이": "3 Nephi",
    "제4니파이": "4 Nephi",
    "조셉 스미스—마태": "Joseph Smith-Matthew",
    "조셉 스미스—역사": "Joseph Smith-History",
    "창세기": "Genesis",
    "출애굽기": "Exodus",
    "하박국": "Habakkuk",
    "학개": "Haggai",
    "호세า": "Hosea",
    "회복 선언문": "Restoration Proclamation",
    "히브리서": "Hebrews",
    "힐라맨서": "Helaman",
};

/**
 * Normalizes any book name to its English key if possible.
 */
export const identifyBookKey = (bookName: string): string => {
    // 1. Try common identity map (with trimming)
    const cleanName = bookName.trim();
    const mapped = BOOK_IDENTITY_MAP[cleanName];
    if (mapped) return mapped;

    // 2. Try case-insensitive comparison
    const lower = cleanName.toLowerCase();
    for (const [key, value] of Object.entries(BOOK_IDENTITY_MAP)) {
        if (key.toLowerCase() === lower) return value;
    }
    
    return cleanName;
};
