import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const LOCALES_DIR = path.resolve(__dirname, '../src/locales');
const CONFIG_DIR = path.resolve(__dirname, '../src/config');
const LANGUAGES_FILE = path.join(CONFIG_DIR, 'languages.ts');
const METADATA_FILE = path.join(LOCALES_DIR, 'scripture-metadata.ts');

const EXCLUDED_FILES = new Set([
    'i18n.ts',
    'registry.ts',
    'scripture-metadata.ts',
    'initial-translations.ts'
]);

interface LocaleMeta {
    code: string;
    name: string;
    englishName: string;
    flag: string;
    ldsCode: string;
    translationKey?: string;
}

interface LocaleContent {
    _meta?: LocaleMeta;
    scriptures?: Record<string, string>;
    books?: Record<string, string>;
    noteLabels?: Record<string, string>;
    placeholders?: Record<string, string>;
    groupChat?: {
        category?: string;
        chapter?: string;
        comment?: string;
        [key: string]: unknown;
    };
    [key: string]: unknown;
}

interface ExtractedMetadata {
    scriptures: Record<string, string>;
    books: Record<string, string>;
    noteLabels: Record<string, string>;
    placeholders: Record<string, string>;
    groupChat: {
        category?: string;
        chapter?: string;
        comment?: string;
    };
}

// Preferred ordering for established core languages
const PREFERRED_ORDER = ['en', 'ja', 'pt', 'zho', 'es', 'vi', 'th', 'ko', 'tl', 'sw', 'it'];

async function syncI18n() {
    console.log('🔄 Syncing i18n configurations and scripture metadata...');

    const files = fs.readdirSync(LOCALES_DIR)
        .filter(f => (f.endsWith('.ts') || f.endsWith('.js')) && !EXCLUDED_FILES.has(f))
        .sort((a, b) => {
            const langA = path.basename(a, path.extname(a));
            const langB = path.basename(b, path.extname(b));
            const idxA = PREFERRED_ORDER.indexOf(langA);
            const idxB = PREFERRED_ORDER.indexOf(langB);
            if (idxA !== -1 && idxB !== -1) return idxA - idxB;
            if (idxA !== -1) return -1;
            if (idxB !== -1) return 1;
            return langA.localeCompare(langB);
        });

    const discoveredLanguages: Array<{
        code: string;
        name: string;
        englishName: string;
        flag: string;
        ldsCode: string;
        translationKey: string;
    }> = [];

    const metadataByCode: Record<string, ExtractedMetadata> = {};

    for (const file of files) {
        const langCode = path.basename(file, path.extname(file));
        const filePath = path.join(LOCALES_DIR, file);
        const mod = await import(pathToFileURL(filePath).href);
        const data: LocaleContent = mod.default || mod;

        const meta = data._meta || {
            code: langCode,
            name: langCode,
            englishName: langCode,
            flag: '🌐',
            ldsCode: langCode
        };

        const primaryEnglishWord = meta.englishName.split(/[\s(]/)[0].toLowerCase();
        const translationKey = meta.translationKey || `languages.${primaryEnglishWord}`;

        discoveredLanguages.push({
            code: meta.code || langCode,
            name: meta.name || langCode,
            englishName: meta.englishName || langCode,
            flag: meta.flag || '🌐',
            ldsCode: meta.ldsCode || langCode,
            translationKey
        });

        metadataByCode[langCode] = {
            scriptures: (data.scriptures && typeof data.scriptures === 'object' ? data.scriptures : {}) as Record<string, string>,
            books: (data.books && typeof data.books === 'object' ? data.books : {}) as Record<string, string>,
            noteLabels: (data.noteLabels && typeof data.noteLabels === 'object' ? data.noteLabels : {}) as Record<string, string>,
            placeholders: (data.placeholders && typeof data.placeholders === 'object' ? data.placeholders : {}) as Record<string, string>,
            groupChat: {
                category: typeof data.groupChat?.category === 'string' ? data.groupChat.category : undefined,
                chapter: typeof data.groupChat?.chapter === 'string' ? data.groupChat.chapter : undefined,
                comment: typeof data.groupChat?.comment === 'string' ? data.groupChat.comment : undefined,
            }
        };
    }

    // 1. Generate src/config/languages.ts
    const languageUnionType = discoveredLanguages.map(l => `'${l.code}'`).join(' | ');

    const languagesContent = `// Auto-generated by scripts/sync-i18n.ts - DO NOT EDIT DIRECTLY
// To add a new language, simply create src/locales/<lang>.ts with a valid _meta section.

export type Language = ${languageUnionType};

export type TranslationValue = string | string[] | NestedTranslations;
export interface NestedTranslations {
    [key: string]: TranslationValue;
}

export interface LanguageConfig {
    code: Language;
    name: string;
    englishName: string;
    translationKey: string;
    flag: string;
    ldsCode: string;
}

export const LANGUAGES: readonly LanguageConfig[] = ${JSON.stringify(discoveredLanguages, null, 4)} as const;

export const SUPPORTED_LANGUAGES: Language[] = LANGUAGES.map(lang => lang.code);
export const DEFAULT_LANGUAGE: Language = 'en';

function getLanguageConfig(code: string): LanguageConfig | undefined {
    return LANGUAGES.find(lang => lang.code === code);
}

export function getLdsLanguageCode(code: string): string {
    const config = getLanguageConfig(code);
    return config ? config.ldsCode : 'eng';
}
`;

    fs.writeFileSync(LANGUAGES_FILE, languagesContent, 'utf-8');
    console.log(`✅ Generated ${path.relative(process.cwd(), LANGUAGES_FILE)} (${discoveredLanguages.length} languages)`);

    // 2. Generate src/locales/scripture-metadata.ts
    const metadataContent = `/**
 * Auto-generated by scripts/sync-i18n.ts - DO NOT EDIT DIRECTLY
 * Standalone Scripture & Book Metadata Registry.
 * Extracted from full locale dictionaries to allow dynamic loading of language files
 * without bloating the initial entry bundle.
 */

export interface LocaleDefinition {
    scriptures?: Record<string, string>;
    noteLabels?: Record<string, string>;
    placeholders?: Record<string, string>;
    groupChat?: {
        category?: string;
        chapter?: string;
        comment?: string;
        [key: string]: unknown;
    };
    books?: Record<string, string>;
}

export const LOCALES_BY_CODE: Record<string, LocaleDefinition> = ${JSON.stringify(metadataByCode, null, 4)};

export const ALL_LOCALES: LocaleDefinition[] = Object.values(LOCALES_BY_CODE);
`;

    fs.writeFileSync(METADATA_FILE, metadataContent, 'utf-8');
    console.log(`✅ Generated ${path.relative(process.cwd(), METADATA_FILE)}`);
    console.log('🎉 i18n synchronization complete!\n');
}

syncI18n().catch(err => {
    console.error('❌ Failed to sync i18n:', err);
    process.exit(1);
});
